version: '3.8'

name: authservice
services:
  nginx:
    container_name: authservice-nginx
    image: nginx:1.25-alpine
    volumes:
      - ./.docker/nginx/conf:/etc/nginx/conf.d:ro
      - .:/var/www/html:ro
    ports:
      - ${DOCKER_WEB_PORT}:80
    restart: unless-stopped
    depends_on:
      - php
    links:
      - php
  php:
    container_name: authservice-php
    build: .docker/php
    volumes:
      - ./.docker/php/conf:/usr/local/etc/php/conf.d:ro
      - .:/var/www/html:ro
      - ./vendor:/var/www/html/vendor:rw
      - ./composer.json:/var/www/html/composer.json:rw
      - ./composer.lock:/var/www/html/composer.lock:rw
      - ./.env:/var/www/html/.env:rw
      - ./logs:/var/www/html/logs:rw
      - ./var/cache:/var/www/html/var/cache:rw
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:16-alpine
    container_name: authservice-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - authservice_db:/var/lib/postgresql/data:rw
    restart: unless-stopped

volumes:
  authservice_db:
    name: authservice_db